docker-compose-yaml: docker-compose.yml

project: demo-api-druxtjs-org

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    - run:
        name: drush si
        command: drush -y si demo_umami
        service: cli

    # - run:
    #     name: drush cim
    #     command: drush -y cim
    #     service: cli
    # - run:
    #     name: drush updb
    #     command: drush -y updb
    #     service: cli
    # - run:
    #     name: drush cr
    #     command: drush -y cr
    #     service: cli



environments:
  9.x:
    routes:
      - nginx:
        - demo-api.druxtjs.org
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
